name: Ruby

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Install dependencies
        run: bundle install

      - name: Setup sinatra application
        run: bundle exec ruby app.rb & sleep 1

      - name: Run RSpec
        run: bundle exec rspec -t ~capybara
